---
name: Linux

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: pip install meson ninja
      - run: meson setup build/
        env:
          CC: gcc
      - name: Test
        run: ninja -C build test

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: brew install gcc
      - run: pip install meson ninja
      - run: meson setup build/
        env:
          CC: gcc
      - name: Test
        run: ninja -C build test
